version: '3.8'
services:
  dev-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - app-network
  redis: 
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - app-network
networks:
  app-network: